server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /consumer-api/ {
        proxy_pass http://consumer-service:8081/;
        proxy_set_header Host $host;
        proxy_set_header Authorization $http_authorization;
    }
    location /provider-api/ {
        proxy_pass http://provider-service:8082/;
        proxy_set_header Host $host;
        proxy_set_header Authorization $http_authorization;
    }
    location /order-api/ {
        proxy_pass http://order-service:8083/;
        proxy_set_header Host $host;
        proxy_set_header Authorization $http_authorization;
    }
}
